name: CI/CD for BigNum Operations

on:
  push:
#    branches:
#      - main
#      - base_yoosunghwan

jobs:
  test_main:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache SageMath
        uses: actions/cache@v4
        with:
          path: /usr/local/sage
          key: ${{ runner.os }}-sagemath-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-sagemath-

      - name: Install SageMath
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y sagemath
          sudo mkdir -p /usr/local/sage

      - name: Verfiy SageMath installation
        run: |
          sage --version

      - name: Run SageMath tests
        run: |
          sage BigNum/sage_test/test.sage | tee sage_output.log